# Generated by Django 4.2.7 on 2023-11-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_answer_related_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='related_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_player_relationship', to='game.player'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='related_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_question_relationship', to='game.question'),
        ),
    ]
