# Generated by Django 4.2.7 on 2023-11-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_answer_related_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPoint', models.BooleanField(default=False)),
                ('related_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerassign_answer_relationship', to='game.answer')),
                ('related_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerassign_player_relationship', to='game.player')),
            ],
        ),
    ]
