# Generated by Django 4.2.7 on 2023-11-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_roomround'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_code',
            field=models.CharField(default=123, max_length=11),
            preserve_default=False,
        ),
    ]
