# Generated by Django 4.2.7 on 2023-11-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_answer_answer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomround',
            name='mode',
            field=models.CharField(choices=[('single', 'SINGLE'), ('multiple', 'MULTIPLE')], default='multiple', max_length=10),
        ),
    ]
