# Generated by Django 4.2.7 on 2023-11-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_roomround_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_mode',
            field=models.CharField(choices=[('mixed', 'MIXED'), ('single', 'SINGLE'), ('multiple', 'MULTIPLE')], default='mixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_rounds',
            field=models.IntegerField(default=4),
        ),
    ]
