# Generated by Django 4.2.7 on 2023-12-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_room_game_mode_alter_room_max_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_mode',
            field=models.CharField(choices=[('text', 'TEXT'), ('draw', 'DRAW'), ('player', 'PLAYER')], default='text', max_length=16),
        ),
        migrations.AlterField(
            model_name='roomround',
            name='mode',
            field=models.CharField(choices=[('single', 'SINGLE'), ('multiple', 'MULTIPLE'), ('draw', 'DRAW')], default='multiple', max_length=10),
        ),
    ]
