# Generated by Django 4.1 on 2023-12-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_question_question_mode_alter_roomround_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='global_key',
            field=models.CharField(default=-4444, max_length=128),
            preserve_default=False,
        ),
    ]
