# Generated by Django 4.1 on 2023-12-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_question_global_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='global_key',
            field=models.CharField(max_length=64),
        ),
    ]
